using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.IO;

namespace Richard2.Models
{
    public class DataRepository
    {
        public static IList<Employee> EmployeeData = null;
        public static IList<Employee> GetEmployees()
        {
            if (EmployeeData == null)
            {
                EmployeeData = new List<Employee>();
                EmployeeData.Add(new Employee() { EmployeeID = 19, Name = "Cathi Payne", Position = "Sales Representative", CompanyID = 0 });
                EmployeeData.Add(new Employee() { EmployeeID = 20, Name = "Maria Green", Position = "Vice President, Sales", CompanyID = 5 });
                //EmployeeData.Add(new Employee() { EmployeeID = 21, Name = "Mike Payne", Position = "Sales Representative", CompanyID = 5 });
                //EmployeeData.Add(new Employee() { EmployeeID = 22, Name = "Jean Lawson", Position = "Sales Representative", CompanyID = 5 });
                //EmployeeData.Add(new Employee() { EmployeeID = 23, Name = "Brad Pitt", Position = "Sales Manager", CompanyID = 5 });
                //EmployeeData.Add(new Employee() { EmployeeID = 24, Name = "Jona Lomu", Position = "Sales Representative", CompanyID = 4 });
                //EmployeeData.Add(new Employee() { EmployeeID = 25, Name = "Michael Jones", Position = "Sales Representative", CompanyID = 4 });
                //EmployeeData.Add(new Employee() { EmployeeID = 26, Name = "Michele Pfeiffer", Position = "Inside Sales Coordinator", CompanyID = 1 });
                //EmployeeData.Add(new Employee() { EmployeeID = 27, Name = "Julia Roberts", Position = "Sales Representative", CompanyID = 2 });
                //EmployeeData.Add(new Employee() { EmployeeID = 28, Name = "Abbate, Anthony", Position = "Social Studies", CompanyID = 2 });
                //EmployeeData.Add(new Employee() { EmployeeID = 29, Name = "Abbate, Anthony", Position = "Social Studies", CompanyID = 4 });
                //EmployeeData.Add(new Employee() { EmployeeID = 30, Name = "Abermanis, Nichole", Position = "Kindergarten", CompanyID = 4 });
                //EmployeeData.Add(new Employee() { EmployeeID = 31, Name = "Adams, Patricia", Position = "Art", CompanyID = 4 });
                //EmployeeData.Add(new Employee() { EmployeeID = 32, Name = "Admiraal, Matthew", Position = "Math", CompanyID = 4 });
                //EmployeeData.Add(new Employee() { EmployeeID = 33, Name = "Aills, Claudia", Position = "1st Grade", CompanyID = 2 });
                //EmployeeData.Add(new Employee() { EmployeeID = 34, Name = "Alleman, Catherine", Position = "2nd Grade", CompanyID = 4 });
                //EmployeeData.Add(new Employee() { EmployeeID = 35, Name = "Allerton, Liz", Position = "GSRP Teacher Assistant", CompanyID = 0 });
                //EmployeeData.Add(new Employee() { EmployeeID = 36, Name = "Allor, Elizabeth", Position = "4th Grade", CompanyID = 4 });
                //EmployeeData.Add(new Employee() { EmployeeID = 37, Name = "Altermatt, Maureen", Position = "Principal", CompanyID = 2 });
                //EmployeeData.Add(new Employee() { EmployeeID = 38, Name = "Amos, Amanda", Position = "Resource Room", CompanyID = 2 });
                //EmployeeData.Add(new Employee() { EmployeeID = 39, Name = "Anderson, Michele", Position = "Kindergarten", CompanyID = 4 });
                //EmployeeData.Add(new Employee() { EmployeeID = 40, Name = "Anderson, Sara", Position = "4th Grade ", CompanyID = 4 });
                //EmployeeData.Add(new Employee() { EmployeeID = 41, Name = "Andreski, Kristine", Position = "World Language", CompanyID = 4 });
                //EmployeeData.Add(new Employee() { EmployeeID = 42, Name = "Andrews, Stacy", Position = "4th Grade", CompanyID = 2 });
                //EmployeeData.Add(new Employee() { EmployeeID = 43, Name = "Angelosanto, Kellie", Position = "Data Processor", CompanyID = 4 });
                //EmployeeData.Add(new Employee() { EmployeeID = 44, Name = "Arbenowske, Ann", Position = "Bookkeeper", CompanyID = 4 });
                //EmployeeData.Add(new Employee() { EmployeeID = 45, Name = "Arbini, Anthony", Position = "Art", CompanyID = 4 });
                //EmployeeData.Add(new Employee() { EmployeeID = 46, Name = "Arbini, Anthony", Position = "Art", CompanyID = 4 });
                //EmployeeData.Add(new Employee() { EmployeeID = 47, Name = "Arbini, Anthony", Position = "Art", CompanyID = 2 });
                //EmployeeData.Add(new Employee() { EmployeeID = 48, Name = "Armstead, Tracy", Position = "Caregiver", CompanyID = 4 });
                //EmployeeData.Add(new Employee() { EmployeeID = 49, Name = "Armstrong, Janet", Position = "1st Grade", CompanyID = 4 });
                //EmployeeData.Add(new Employee() { EmployeeID = 50, Name = "Armstrong, Shawn", Position = "Bus Driver", CompanyID = 0 });
                //EmployeeData.Add(new Employee() { EmployeeID = 51, Name = "Ashe, Amanda", Position = "Custodian", CompanyID = 4 });
                //EmployeeData.Add(new Employee() { EmployeeID = 52, Name = "Ashe, Steve", Position = "Roving Engineer", CompanyID = 2 });
                //EmployeeData.Add(new Employee() { EmployeeID = 53, Name = "Atchison, Eric", Position = "Custodian", CompanyID = 4 });
                //EmployeeData.Add(new Employee() { EmployeeID = 54, Name = "Athey, Sarah", Position = "History", CompanyID = 4 });
                //EmployeeData.Add(new Employee() { EmployeeID = 55, Name = "Atwell, Amy", Position = "Special Ed - CI", CompanyID = 0 });
                //EmployeeData.Add(new Employee() { EmployeeID = 56, Name = "Bache, Kathy", Position = "Bus Driver", CompanyID = 1 });
                //EmployeeData.Add(new Employee() { EmployeeID = 57, Name = "Baidel, Katherine", Position = "Speech & Language Pathologist", CompanyID = 2 });
                //EmployeeData.Add(new Employee() { EmployeeID = 58, Name = "Baker, Lynn", Position = "Bus Driver", CompanyID = 3 });
                //EmployeeData.Add(new Employee() { EmployeeID = 59, Name = "Baker, Melissa", Position = "Assistant Superintendent", CompanyID = 4 });
                //EmployeeData.Add(new Employee() { EmployeeID = 60, Name = "Baker, Ross", Position = "Social Studies", CompanyID = 0 });
                //EmployeeData.Add(new Employee() { EmployeeID = 61, Name = "Ball, Ayana", Position = "Business/Math", CompanyID = 2 });
                //EmployeeData.Add(new Employee() { EmployeeID = 62, Name = "Ball, Ayana", Position = "Business/Math", CompanyID = 2 });
                //EmployeeData.Add(new Employee() { EmployeeID = 63, Name = "Banchoff, Jill", Position = "Preschool Teacher Assistant", CompanyID = 3 });
                //EmployeeData.Add(new Employee() { EmployeeID = 64, Name = "Bardsley, Diane", Position = "Counselor", CompanyID = 4 });
                //EmployeeData.Add(new Employee() { EmployeeID = 65, Name = "Barlow, Patricia", Position = "Para Educator", CompanyID = 0 });
                //EmployeeData.Add(new Employee() { EmployeeID = 66, Name = "Barnett, Marsha", Position = "Restorative Practice", CompanyID = 4 });
                //EmployeeData.Add(new Employee() { EmployeeID = 67, Name = "Barnett, Marsha", Position = "Restorative Practice", CompanyID = 2 });
                //EmployeeData.Add(new Employee() { EmployeeID = 68, Name = "Barone, Anne", Position = "3rd Grade", CompanyID = 3 });
                //EmployeeData.Add(new Employee() { EmployeeID = 69, Name = "Barranca, Natalie", Position = "Special Ed ", CompanyID = 4 });
                //EmployeeData.Add(new Employee() { EmployeeID = 70, Name = "Barshaw, Jennifer", Position = "Social Studies", CompanyID = 4 });
                //EmployeeData.Add(new Employee() { EmployeeID = 71, Name = "Beagle, Donald", Position = "Board Member", CompanyID = 4 });
                //EmployeeData.Add(new Employee() { EmployeeID = 72, Name = "Becker, Amanda", Position = "Alternative Ed", CompanyID = 2 });
                //EmployeeData.Add(new Employee() { EmployeeID = 73, Name = "Beckstein, April", Position = "Para Educator", CompanyID = 3 });
                //EmployeeData.Add(new Employee() { EmployeeID = 74, Name = "Beckstein, Shelly", Position = "Site Leader", CompanyID = 4 });
                //EmployeeData.Add(new Employee() { EmployeeID = 75, Name = "Bedich, Lauren", Position = "Careers/Business Buddies", CompanyID = 0 });
                //EmployeeData.Add(new Employee() { EmployeeID = 76, Name = "Beemer, Patrick", Position = "Mechanic", CompanyID = 1 });
                //EmployeeData.Add(new Employee() { EmployeeID = 77, Name = "Belanger, Amanda", Position = "Site Leader", CompanyID = 2 });
                //EmployeeData.Add(new Employee() { EmployeeID = 78, Name = "Bell, Katie", Position = "Speech & Language Pathologist", CompanyID = 3 });
                //EmployeeData.Add(new Employee() { EmployeeID = 79, Name = "Besco, Tamara", Position = "Math/Lang Arts", CompanyID = 4 });
                //EmployeeData.Add(new Employee() { EmployeeID = 80, Name = "Besso, MaryKay", Position = "Bus Driver", CompanyID = 0 });
                //EmployeeData.Add(new Employee() { EmployeeID = 81, Name = "Best, Cheryl", Position = "Custodian", CompanyID = 4 });
                //EmployeeData.Add(new Employee() { EmployeeID = 82, Name = "Bethel, Stacie", Position = "Data Processor", CompanyID = 2 });
                //EmployeeData.Add(new Employee() { EmployeeID = 83, Name = "Beutel, Adam", Position = "Assistant Athletic Director", CompanyID = 3 });
                //EmployeeData.Add(new Employee() { EmployeeID = 84, Name = "Bewersdorf, Melissa", Position = "English", CompanyID = 4 });
                //EmployeeData.Add(new Employee() { EmployeeID = 85, Name = "Blandina, Mary", Position = "Cook/Baker", CompanyID = 4 });
                //EmployeeData.Add(new Employee() { EmployeeID = 86, Name = "Blasy, Jill", Position = "Resource Room", CompanyID = 4 });
                //EmployeeData.Add(new Employee() { EmployeeID = 87, Name = "Blaszczyk, Linda", Position = "Dispatcher", CompanyID = 2 });
                //EmployeeData.Add(new Employee() { EmployeeID = 88, Name = "Bogard, Danielle", Position = "Speech & Language Pathologist", CompanyID = 3 });
                //EmployeeData.Add(new Employee() { EmployeeID = 89, Name = "Bolton, Amy", Position = "Counselor", CompanyID = 4 });
                //EmployeeData.Add(new Employee() { EmployeeID = 90, Name = "Bond, Mary", Position = "Para Educator", CompanyID = 0 });
                //EmployeeData.Add(new Employee() { EmployeeID = 91, Name = "Bondy, Sharon", Position = "1st Grade", CompanyID = 4 });
                //EmployeeData.Add(new Employee() { EmployeeID = 92, Name = "Boutette, Joan", Position = "2nd Grade", CompanyID = 2 });
                //EmployeeData.Add(new Employee() { EmployeeID = 93, Name = "Bowman, Carmen", Position = "Custodian", CompanyID = 4 });
                //EmployeeData.Add(new Employee() { EmployeeID = 94, Name = "Boynton, Theresa", Position = "2nd Grade", CompanyID = 4 });
                //EmployeeData.Add(new Employee() { EmployeeID = 95, Name = "Brainard, Sheri", Position = "2nd Grade", CompanyID = 0 });
                //EmployeeData.Add(new Employee() { EmployeeID = 96, Name = "Brandon, Denise", Position = "Secretary", CompanyID = 4 });
                //EmployeeData.Add(new Employee() { EmployeeID = 97, Name = "Brannon, Christopher", Position = "Physics", CompanyID = 2 });
                //EmployeeData.Add(new Employee() { EmployeeID = 98, Name = "Bratcher, Misty", Position = "Physical Education", CompanyID = 3 });
                //EmployeeData.Add(new Employee() { EmployeeID = 99, Name = "Bratt, Brenda", Position = "Social Studies", CompanyID = 4 });
                //EmployeeData.Add(new Employee() { EmployeeID = 100, Name = "Brawner, Karen", Position = "Kitchen Manager", CompanyID = 0 });
                //EmployeeData.Add(new Employee() { EmployeeID = 101, Name = "Brehmer, Timothy", Position = "History", CompanyID = 4 });
                //EmployeeData.Add(new Employee() { EmployeeID = 102, Name = "Breier, Martha", Position = "1st Grade", CompanyID = 2 });
                //EmployeeData.Add(new Employee() { EmployeeID = 103, Name = "Brengle, Ellen", Position = "ESL Teacher", CompanyID = 3 });
                //EmployeeData.Add(new Employee() { EmployeeID = 104, Name = "Brengle, Ellen", Position = "ESL Teacher", CompanyID = 4 });
                //EmployeeData.Add(new Employee() { EmployeeID = 105, Name = "Brennan, James", Position = "English, Yearbook", CompanyID = 0 });
                //EmployeeData.Add(new Employee() { EmployeeID = 106, Name = "Brennan, Joan", Position = "Math", CompanyID = 4 });
                //EmployeeData.Add(new Employee() { EmployeeID = 107, Name = "Brennan, Michelle", Position = "Social Worker", CompanyID = 2 });
                //EmployeeData.Add(new Employee() { EmployeeID = 108, Name = "Bresler, Wendy", Position = "Cook/Baker", CompanyID = 4 });
                //EmployeeData.Add(new Employee() { EmployeeID = 109, Name = "Breslin, Gina", Position = "Kindergarten", CompanyID = 4 });
                //EmployeeData.Add(new Employee() { EmployeeID = 110, Name = "Brickey, John", Position = "Principal", CompanyID = 0 });
                //EmployeeData.Add(new Employee() { EmployeeID = 111, Name = "Briggs, Stacey", Position = "English", CompanyID = 4 });
                //EmployeeData.Add(new Employee() { EmployeeID = 112, Name = "Briggs, Tracy", Position = "Bus Driver", CompanyID = 2 });
                //EmployeeData.Add(new Employee() { EmployeeID = 113, Name = "Briggs, Valerie", Position = "Bus Driver", CompanyID = 3 });
                //EmployeeData.Add(new Employee() { EmployeeID = 114, Name = "Britton, Dayna", Position = "Biology", CompanyID = 4 });
                //EmployeeData.Add(new Employee() { EmployeeID = 115, Name = "Brown, Jennifer", Position = "Physical Education", CompanyID = 0 });
                //EmployeeData.Add(new Employee() { EmployeeID = 116, Name = "Brown, Marissa", Position = "5th Grade", CompanyID = 4 });
                //EmployeeData.Add(new Employee() { EmployeeID = 117, Name = "Brown, Mary", Position = "Para Educator", CompanyID = 2 });
                //EmployeeData.Add(new Employee() { EmployeeID = 118, Name = "Browne, Linda", Position = "Para Educator", CompanyID = 4 });
                //EmployeeData.Add(new Employee() { EmployeeID = 119, Name = "Brummer, Steven", Position = "Board Member", CompanyID = 4 });
                //EmployeeData.Add(new Employee() { EmployeeID = 120, Name = "Brun, Mary", Position = "Principal", CompanyID = 0 });
                //EmployeeData.Add(new Employee() { EmployeeID = 121, Name = "Bugar, Jennifer", Position = "Resource Room", CompanyID = 1 });
                //EmployeeData.Add(new Employee() { EmployeeID = 122, Name = "Bullinger, Christopher", Position = "Manager of District Fac. & Grounds", CompanyID = 2 });
                //EmployeeData.Add(new Employee() { EmployeeID = 123, Name = "Burch, John", Position = "Social Studies", CompanyID = 4 });
                //EmployeeData.Add(new Employee() { EmployeeID = 124, Name = "Burgess, Anne", Position = "Speech & Language Pathologist", CompanyID = 4 });
                //EmployeeData.Add(new Employee() { EmployeeID = 125, Name = "Burgess, Anne", Position = "Speech", CompanyID = 0 });
                //EmployeeData.Add(new Employee() { EmployeeID = 126, Name = "Burgess, James", Position = "Custodian", CompanyID = 4 });
                //EmployeeData.Add(new Employee() { EmployeeID = 127, Name = "Burke, Kevin", Position = "Economics", CompanyID = 2 });
                //EmployeeData.Add(new Employee() { EmployeeID = 128, Name = "Burkhart, Arlene", Position = "Reading Recovery", CompanyID = 3 });
                //EmployeeData.Add(new Employee() { EmployeeID = 129, Name = "Burton, Chena", Position = "Dispatcher", CompanyID = 4 });
                //EmployeeData.Add(new Employee() { EmployeeID = 130, Name = "Bushey, Michelle", Position = "Special Ed - CI", CompanyID = 0 });
                //EmployeeData.Add(new Employee() { EmployeeID = 131, Name = "Bussert, Cathleen", Position = "Data Processor", CompanyID = 4 });
                //EmployeeData.Add(new Employee() { EmployeeID = 132, Name = "Bussert, Cathleen", Position = "Data Processor", CompanyID = 2 });
                //EmployeeData.Add(new Employee() { EmployeeID = 133, Name = "Butterfield, Joyce", Position = "Data Processor", CompanyID = 4 });
                //EmployeeData.Add(new Employee() { EmployeeID = 134, Name = "Cacani, Hena", Position = "Cook/Baker", CompanyID = 4 });
                //EmployeeData.Add(new Employee() { EmployeeID = 135, Name = "Cadwallader, Jon", Position = "Spanish", CompanyID = 4 });
                //EmployeeData.Add(new Employee() { EmployeeID = 136, Name = "Cadwallader, Jon", Position = "Spanish", CompanyID = 4 });
                //EmployeeData.Add(new Employee() { EmployeeID = 137, Name = "Callery, James", Position = "Fleet Supervisor", CompanyID = 2 });
                //EmployeeData.Add(new Employee() { EmployeeID = 138, Name = "Callovi, Dennis", Position = "3rd/4th Grade", CompanyID = 2 });
                //EmployeeData.Add(new Employee() { EmployeeID = 139, Name = "Candelieri, Michelle", Position = "Math/English", CompanyID = 4 });
                //EmployeeData.Add(new Employee() { EmployeeID = 140, Name = "Candelieri, Michelle", Position = "Math/English", CompanyID = 0 });
                //EmployeeData.Add(new Employee() { EmployeeID = 141, Name = "Carravallah, David", Position = "Math", CompanyID = 2 });
                //EmployeeData.Add(new Employee() { EmployeeID = 142, Name = "Carrel, Anne", Position = "Office Clerk", CompanyID = 2 });
                //EmployeeData.Add(new Employee() { EmployeeID = 143, Name = "Carroll, Jerry", Position = "Building Engineer", CompanyID = 3 });
                //EmployeeData.Add(new Employee() { EmployeeID = 144, Name = "Carroll, Jimmie", Position = "Custodian", CompanyID = 4 });
                //EmployeeData.Add(new Employee() { EmployeeID = 145, Name = "Carroll, Marion", Position = "Custodian", CompanyID = 0 });
                //EmployeeData.Add(new Employee() { EmployeeID = 146, Name = "Casey, Michael", Position = "Director of Operations", CompanyID = 2 });
                //EmployeeData.Add(new Employee() { EmployeeID = 147, Name = "Castle, Sharon", Position = "Bookkeeper", CompanyID = 2 });
                //EmployeeData.Add(new Employee() { EmployeeID = 148, Name = "Cauchi, Maureen", Position = "Language Arts, English", CompanyID = 3 });
                //EmployeeData.Add(new Employee() { EmployeeID = 149, Name = "Caves, Marty", Position = "Science", CompanyID = 4 });
                //EmployeeData.Add(new Employee() { EmployeeID = 150, Name = "Cawetzka, Martha", Position = "English", CompanyID = 0 });
                //EmployeeData.Add(new Employee() { EmployeeID = 151, Name = "Cervenak, Meridith", Position = "Social Worker", CompanyID = 1 });
                //EmployeeData.Add(new Employee() { EmployeeID = 152, Name = "Chamberlin, Justin", Position = "Social Studies", CompanyID = 2 });
                //EmployeeData.Add(new Employee() { EmployeeID = 153, Name = "Cherry, David", Position = "4th Grade", CompanyID = 3 });
                //EmployeeData.Add(new Employee() { EmployeeID = 154, Name = "Cherry, Melissa", Position = "4th Grade", CompanyID = 4 });
                //EmployeeData.Add(new Employee() { EmployeeID = 155, Name = "Chio, Nancy", Position = "Bus Driver", CompanyID = 0 });
                //EmployeeData.Add(new Employee() { EmployeeID = 156, Name = "Chrzanowski, Mark", Position = "Physical Education", CompanyID = 1 });
                //EmployeeData.Add(new Employee() { EmployeeID = 157, Name = "Chrzanowski, Mark", Position = "Physical Education", CompanyID = 2 });
                //EmployeeData.Add(new Employee() { EmployeeID = 158, Name = "Chrzanowski, Sarah", Position = "Science", CompanyID = 3 });
                //EmployeeData.Add(new Employee() { EmployeeID = 159, Name = "Chudy-Bowman, Linda", Position = "Assistant Principal", CompanyID = 4 });
                //EmployeeData.Add(new Employee() { EmployeeID = 160, Name = "Cibrario, Christina", Position = "Math", CompanyID = 0 });
                //EmployeeData.Add(new Employee() { EmployeeID = 161, Name = "Clark, Jennifer", Position = "Physical Education", CompanyID = 1 });
                //EmployeeData.Add(new Employee() { EmployeeID = 162, Name = "Clark, Jennifer", Position = "Physical Education", CompanyID = 2 });
                //EmployeeData.Add(new Employee() { EmployeeID = 163, Name = "Clearwood, Mary Ann", Position = "Caregiver", CompanyID = 3 });
                //EmployeeData.Add(new Employee() { EmployeeID = 164, Name = "Cleveland, Carey", Position = "3rd Grade", CompanyID = 4 });
                //EmployeeData.Add(new Employee() { EmployeeID = 165, Name = "Connors, Brittany", Position = "1st", CompanyID = 0 });
                //EmployeeData.Add(new Employee() { EmployeeID = 166, Name = "Convery, Jacqueline", Position = "Reading Recovery", CompanyID = 1 });
                //EmployeeData.Add(new Employee() { EmployeeID = 167, Name = "Cook, Audrey", Position = "Bus Driver", CompanyID = 2 });
                //EmployeeData.Add(new Employee() { EmployeeID = 168, Name = "Cooper, Stacy", Position = "Principal", CompanyID = 3 });
                //EmployeeData.Add(new Employee() { EmployeeID = 169, Name = "Cope, Jackie", Position = "1st Grade", CompanyID = 4 });
                //EmployeeData.Add(new Employee() { EmployeeID = 170, Name = "Cope, Marc", Position = "Bus Driver", CompanyID = 0 });
                //EmployeeData.Add(new Employee() { EmployeeID = 171, Name = "Coppola, Gino", Position = "Custodian", CompanyID = 1 });
                //EmployeeData.Add(new Employee() { EmployeeID = 172, Name = "Corbin, Jamie", Position = "Language Arts, English", CompanyID = 2 });
                //EmployeeData.Add(new Employee() { EmployeeID = 173, Name = "Corbin, Jamie", Position = "Language Arts, English", CompanyID = 3 });
                //EmployeeData.Add(new Employee() { EmployeeID = 174, Name = "Cort, Kevin", Position = "Band", CompanyID = 4 });
                //EmployeeData.Add(new Employee() { EmployeeID = 175, Name = "Cort, Kevin", Position = "Piano Lab", CompanyID = 0 });
                //EmployeeData.Add(new Employee() { EmployeeID = 176, Name = "Costa, Christopher", Position = "Science", CompanyID = 1 });
                //EmployeeData.Add(new Employee() { EmployeeID = 177, Name = "Covington, Kristina", Position = "Social Worker", CompanyID = 2 });
                //EmployeeData.Add(new Employee() { EmployeeID = 178, Name = "Cox, Chester", Position = "Director of Technology", CompanyID = 3 });
                //EmployeeData.Add(new Employee() { EmployeeID = 179, Name = "Craig, Catherine", Position = "ECC and Kids Club Director", CompanyID = 4 });
                //EmployeeData.Add(new Employee() { EmployeeID = 180, Name = "Curnow, Karen", Position = "Kindergarten", CompanyID = 0 });
                //EmployeeData.Add(new Employee() { EmployeeID = 181, Name = "Curry, Douglas", Position = "Board Member", CompanyID = 1 });
                //EmployeeData.Add(new Employee() { EmployeeID = 182, Name = "Curtis, Wanda", Position = "Secretary", CompanyID = 2 });
                //EmployeeData.Add(new Employee() { EmployeeID = 183, Name = "Dagenhardt, Amy", Position = "Controller", CompanyID = 3 });
                //EmployeeData.Add(new Employee() { EmployeeID = 184, Name = "Dancer, Kim", Position = "Principal", CompanyID = 4 });
                //EmployeeData.Add(new Employee() { EmployeeID = 185, Name = "Dangel, Denise", Position = "Para Educator", CompanyID = 0 });
                //EmployeeData.Add(new Employee() { EmployeeID = 186, Name = "Darket, Michele", Position = "Principals Secretary", CompanyID = 1 });
                //EmployeeData.Add(new Employee() { EmployeeID = 187, Name = "Davis, Constance", Position = "Cook/Baker", CompanyID = 2 });
                //EmployeeData.Add(new Employee() { EmployeeID = 188, Name = "Davis, Eric", Position = "Economics", CompanyID = 3 });
                //EmployeeData.Add(new Employee() { EmployeeID = 189, Name = "Davis, Lori", Position = "5th Grade", CompanyID = 4 });
                //EmployeeData.Add(new Employee() { EmployeeID = 190, Name = "Day, Alyssa", Position = "Kindergarten", CompanyID = 0 });
                //EmployeeData.Add(new Employee() { EmployeeID = 191, Name = "Deakins, Jeanette", Position = "Admin. Assistant", CompanyID = 1 });
                //EmployeeData.Add(new Employee() { EmployeeID = 192, Name = "DeGroat, Jessica", Position = "5th Grade", CompanyID = 2 });
                //EmployeeData.Add(new Employee() { EmployeeID = 193, Name = "DelVecchio, Lindsay", Position = "3rd Grade", CompanyID = 3 });
                //EmployeeData.Add(new Employee() { EmployeeID = 194, Name = "DelVecchio, Lisa", Position = "Assistant Principal", CompanyID = 4 });
                //EmployeeData.Add(new Employee() { EmployeeID = 195, Name = "DeMoss, Shelly", Position = "Science", CompanyID = 0 });
                //EmployeeData.Add(new Employee() { EmployeeID = 196, Name = "Denski, Kendall", Position = "Kindergarten", CompanyID = 4 });
                //EmployeeData.Add(new Employee() { EmployeeID = 197, Name = "Denski, Kendall", Position = "Kindergarten", CompanyID = 2 });
                //EmployeeData.Add(new Employee() { EmployeeID = 198, Name = "DePassio, Christina", Position = "Physical Education", CompanyID = 3 });
                //EmployeeData.Add(new Employee() { EmployeeID = 199, Name = "DePassio, Christina", Position = "Phys. Ed.", CompanyID = 4 });
                //EmployeeData.Add(new Employee() { EmployeeID = 200, Name = "Descavish, Lukas", Position = "5th Grade", CompanyID = 0 });
                //EmployeeData.Add(new Employee() { EmployeeID = 201, Name = "Dietz, Amy", Position = "Speech & Language Pathologist", CompanyID = 4 });
                //EmployeeData.Add(new Employee() { EmployeeID = 202, Name = "Dilorenzo, Roxann", Position = "Custodian", CompanyID = 2 });
                //EmployeeData.Add(new Employee() { EmployeeID = 203, Name = "DiMarco, Jennifer", Position = "Language Arts, English", CompanyID = 3 });
                //EmployeeData.Add(new Employee() { EmployeeID = 204, Name = "DiVitto, Freda", Position = "World Language", CompanyID = 4 });
                //EmployeeData.Add(new Employee() { EmployeeID = 205, Name = "DiVitto, Raymond", Position = "Social Studies", CompanyID = 0 });
                //EmployeeData.Add(new Employee() { EmployeeID = 206, Name = "Dix, Theresa", Position = "Site Leader", CompanyID = 4 });
                //EmployeeData.Add(new Employee() { EmployeeID = 207, Name = "Dixon, Kate", Position = "2nd Grade", CompanyID = 2 });
                //EmployeeData.Add(new Employee() { EmployeeID = 208, Name = "Dobrovic, Cynthia", Position = "Principals Secretary", CompanyID = 3 });
                //EmployeeData.Add(new Employee() { EmployeeID = 209, Name = "Doctrove, Michelle", Position = "Cook/Baker", CompanyID = 4 });
                //EmployeeData.Add(new Employee() { EmployeeID = 210, Name = "Domagala, Barbara", Position = "Para Educator", CompanyID = 0 });
                //EmployeeData.Add(new Employee() { EmployeeID = 211, Name = "Dombrowski, Louanne", Position = "Cook/Baker", CompanyID = 4 });
                //EmployeeData.Add(new Employee() { EmployeeID = 212, Name = "Doree, Karen", Position = "Biology, Chemistry", CompanyID = 2 });
                //EmployeeData.Add(new Employee() { EmployeeID = 213, Name = "Downey, Greg", Position = "Board Member", CompanyID = 3 });
                //EmployeeData.Add(new Employee() { EmployeeID = 214, Name = "Dreher, Amanda", Position = "Resource Room", CompanyID = 4 });
            }
            return EmployeeData;
        }
        public static IList<Company> CompanyData = File.ReadAllLines(@"C:\Users\User\source\repos\Richard2\Richard2\Models\Data\company_list.csv")
                                           .Skip(1)
                                           .Select(v => new Company(v))
                                           .ToList();
        //public static IList<Company> CompanyData = null;
        public static IList<Company> GetCompanies()
        {
            if (CompanyData == null)
            {
                CompanyData = new List<Company>();
                //CompanyData.Add(new Company() {Name = "Emkay Entertainments", Address = "Nobel House, Regent Centre", Town = "Lothian" });
                //CompanyData.Add(new Company() {ID = 20, Name = "The Empire", Address = "Milton Keynes Leisure Plaza", Town = "Buckinghamshire" });
                //CompanyData.Add(new Company() {ID = 21, Name = "Asadul Ltd", Address = "Hophouse", Town = "Essex" });
                //CompanyData.Add(new Company() {ID = 22, Name = "Gargamel", Address = "", Town = "" });

                //CompanyData.Add(new Company() { ID = 0, Name = "Ashley Mark Publishing Company", Address = "1-2 Vance Court", Town = "Tyne & Wear" });
                //CompanyData.Add(new Company() { ID = 1, Name = "MuchMoreMusic Studios", Address = "Unit 29", Town = "London" });
                //CompanyData.Add(new Company() { Name = "Victoria Music Ltd", Address = "Unit 215", Town = "London" });
                //CompanyData.Add(new Company() { Name = "Abacus Agent", Address = "Regent Street", Town = "London" });
                //CompanyData.Add(new Company() { Name = "Atomic", Address = "133 Longacre", Town = "London" });
                //CompanyData.Add(new Company() { Name = "Pyramid Posters", Address = "The Works", Town = "Leicester" });
                //CompanyData.Add(new Company() { Name = "Kingston Smith Financial Services Ltd", Address = "105 St Peter's Street", Town = "Herts" });
                //CompanyData.Add(new Company() { Name = "Garrett Axford PR", Address = "Harbour House", Town = "West Sussex" });
                //CompanyData.Add(new Company() { Name = "Derek Boulton Management", Address = "76 Carlisle Mansions", Town = "London" });
                //CompanyData.Add(new Company() { Name = "Total Concept Management (TCM)", Address = "PO Box 128", Town = "West Yorks" });
                //CompanyData.Add(new Company() { Name = "Billy Russell Management", Address = "Binny Estate", Town = "Edinburgh" });
                //CompanyData.Add(new Company() { Name = "Stage Audio Services", Address = "Unit 2", Town = "Stourbridge" });
                //CompanyData.Add(new Company() { Name = "Windsong International", Address = "Heather Court", Town = "Kent" });
                //CompanyData.Add(new Company() { Name = "Vivante Music Ltd", Address = "32 The Netherlands", Town = "Surrey" });
                //CompanyData.Add(new Company() { Name = "Way to Blue", Address = "First Floor", Town = "London" });
                //CompanyData.Add(new Company() { Name = "Glasgow City Halls", Address = "32 Albion Street", Town = "Lanarkshire" });
                //CompanyData.Add(new Company() { Name = "The List", Address = "14 High St", Town = "Edinburgh" });
                //CompanyData.Add(new Company() { Name = "Wilkinson Turner King", Address = "10A London Road", Town = "Cheshire" });
                //CompanyData.Add(new Company() { Name = "GSC Solicitors", Address = "31-32 Ely Place", Town = "London" });
                //CompanyData.Add(new Company() { Name = "Vanessa Music Co", Address = "35 Tower Way", Town = "Devon" });
                //CompanyData.Add(new Company() { Name = "Regent Records", Address = "PO Box 528", Town = "West Midlands" });
                //CompanyData.Add(new Company() { Name = "BBC Radio Lancashire", Address = "20-26 Darwen St", Town = "Blackburn" });
                //CompanyData.Add(new Company() { Name = "The Citadel Arts Centre", Address = "Waterloo Street", Town = "Merseyside" });
                //CompanyData.Add(new Company() { Name = "Villa Audio Ltd", Address = "Baileys Yard", Town = "Essex" });
                //CompanyData.Add(new Company() { Name = "cave 3", Address = "", Town = "" });
                //CompanyData.Add(new Company() { Name = "Idle Eyes Printshop", Address = "81 Sheen Court", Town = "Surrey" });
                //CompanyData.Add(new Company() { Name = "Miggins Music (UK)", Address = "33 Mandarin Place", Town = "Oxon" });
                //CompanyData.Add(new Company() { Name = "Magic 999", Address = "St Paul's Square", Town = "Lancashire" });
                //CompanyData.Add(new Company() { Name = "Delga Group", Address = "Seaplane House, Riverside Est.", Town = "Kent" });
                //CompanyData.Add(new Company() { Name = "Zane Music", Address = "162 Castle Hill", Town = "Berkshire" });
                //CompanyData.Add(new Company() { Name = "Universal Music Operations", Address = "Chippenham Drive", Town = "Milton Keynes" });
                //CompanyData.Add(new Company() { Name = "Gotham Records", Address = "PO Box 6003", Town = "Birmingham" });
                //CompanyData.Add(new Company() { Name = "Timbuktu Music Ltd", Address = "99C Talbot Road", Town = "London" });
                //CompanyData.Add(new Company() { Name = "Online Music", Address = "Unit 18, Croydon House", Town = "Surrey" });
                //CompanyData.Add(new Company() { Name = "Irish Music Magazine", Address = "11 Clare St", Town = "Ireland" });
                //CompanyData.Add(new Company() { Name = "Savoy Records", Address = "PO Box 271", Town = "Surrey" });
                //CompanyData.Add(new Company() { Name = "Temple Studios", Address = "97A Kenilworth Road", Town = "Middlesex" });
                //CompanyData.Add(new Company() { Name = "Gravity Shack Studio", Address = "Unit 3 ", Town = "London" });
                //CompanyData.Add(new Company() { Name = "Dovehouse Records", Address = "Crabtree Cottage", Town = "Oxon" });
                //CompanyData.Add(new Company() { Name = "Citysounds Ltd", Address = "5 Kirby Street", Town = "London" });
                //CompanyData.Add(new Company() { Name = "Revolver Music Publishing", Address = "152 Goldthorn Hill", Town = "West Midlands" });
                //CompanyData.Add(new Company() { Name = "Jug Of Ale", Address = "43 Alcester Road", Town = "West Midlands" });
                //CompanyData.Add(new Company() { Name = "Isles FM 103", Address = "PO Box 333", Town = "Western Isles" });
                //CompanyData.Add(new Company() { Name = "Headscope", Address = "Headrest", Town = "East Sussex" });
                //CompanyData.Add(new Company() { Name = "Universal Music Ireland", Address = "9 Whitefriars", Town = "Ireland" });
                //CompanyData.Add(new Company() { Name = "Zander Exports", Address = "34 Sapcote Trading Centre", Town = "London" });
                //CompanyData.Add(new Company() { Name = "Midem (UK)", Address = "Walmar House", Town = "London" });
                //CompanyData.Add(new Company() { Name = "La Rocka Studios", Address = "Post Mark House", Town = "London" });
                //CompanyData.Add(new Company() { Name = "Warner Home DVD", Address = "Warner House", Town = "London" });
                //CompanyData.Add(new Company() { Name = "Music Room", Address = "The Old Library", Town = "London" });
                //CompanyData.Add(new Company() { Name = "Blue Planet", Address = "96 York Street", Town = "London" });
                //CompanyData.Add(new Company() { Name = "Dream 107.7FM", Address = "Cater House", Town = "Chelmsford" });
                //CompanyData.Add(new Company() { Name = "Moneypenny Agency", Address = "The Stables, Westwood House", Town = "East Yorks" });
                //CompanyData.Add(new Company() { Name = "Artsun", Address = "18 Sparkle Street", Town = "Manchester" });
                //CompanyData.Add(new Company() { Name = "Clyde 2", Address = "Clydebank Business Park", Town = "Glasgow" });
                //CompanyData.Add(new Company() { Name = "9PR", Address = "65-69 White Lion Street", Town = "London" });
                //CompanyData.Add(new Company() { Name = "River Studio's", Address = "3 Grange Yard", Town = "London" });
                //CompanyData.Add(new Company() { Name = "Start Entertainments Ltd", Address = "3 Warmair House", Town = "Middx" });
                //CompanyData.Add(new Company() { Name = "Vinyl Tap Mail Order Music", Address = "1 Minerva Works", Town = "West Yorkshire" });
                //CompanyData.Add(new Company() { Name = "Passion Music", Address = "20 Blyth  Rd", Town = "Middlesex" });
                //CompanyData.Add(new Company() { Name = "SuperVision Management", Address = "Zeppelin Building", Town = "London" });
                //CompanyData.Add(new Company() { Name = "Lite FM", Address = "2nd Floor", Town = "Peterborough" });
                //CompanyData.Add(new Company() { Name = "ISIS Duplicating Company", Address = "Sales & Production", Town = "Merseyside" });
                //CompanyData.Add(new Company() { Name = "Vanderbeek & Imrie Ltd", Address = "15 Marvig", Town = "Scotland" });
                //CompanyData.Add(new Company() { Name = "Glamorgan University", Address = "Student Union", Town = "Mid Glamorgan" });
                //CompanyData.Add(new Company() { Name = "Web User", Address = "IPC Media", Town = "London " });
                //CompanyData.Add(new Company() { Name = "Farnborough Recreation Centre", Address = "1 Westmead", Town = "Hampshire" });
                //CompanyData.Add(new Company() { Name = "Robert Owens/Musical Directions", Address = "352A Kilburn Lane", Town = "London" });
                //CompanyData.Add(new Company() { Name = "Magick Eye Records", Address = "PO Box 3037", Town = "Berks" });
                //CompanyData.Add(new Company() { Name = "Alexandra Theatre", Address = "Station Street", Town = "West Midlands" });
                //CompanyData.Add(new Company() { Name = "Keda Records", Address = "The Sight And Sound Centre", Town = "Middlesex" });
                //CompanyData.Add(new Company() { Name = "Independiente Ltd", Address = "The Drill Hall", Town = "London" });
                //CompanyData.Add(new Company() { Name = "Shurwood Management", Address = "Tote Hill Cottage", Town = "West Sussex" });
                //CompanyData.Add(new Company() { Name = "Fury Records", Address = "PO Box 52", Town = "Kent" });
                //CompanyData.Add(new Company() { Name = "Northumbria University", Address = "Union Building", Town = "Newcastle upon Tyne" });
                //CompanyData.Add(new Company() { Name = "Pop Muzik", Address = "Haslemere", Town = "W. Sussex" });
                //CompanyData.Add(new Company() { Name = "Jonsongs Music", Address = "3 Farrers Place", Town = "Surrey" });
                //CompanyData.Add(new Company() { Name = "Hermana PR", Address = "Unit 244, Bon Marche Centre", Town = "London" });
                //CompanyData.Add(new Company() { Name = "Sugarcane Music", Address = "32 Blackmore Avenue", Town = "Middlesex" });
                //CompanyData.Add(new Company() { Name = "JFM Records", Address = "11 Alexander House", Town = "London" });
                //CompanyData.Add(new Company() { Name = "Black Market Records", Address = "25 D'Arblay Street", Town = "London" });
                //CompanyData.Add(new Company() { Name = "Float Your Boat Productions", Address = "5 Ralphs Retreat", Town = "Bucks" });
                //CompanyData.Add(new Company() { Name = "Creation Management", Address = "2 Berkley Grove", Town = "London" });
                //CompanyData.Add(new Company() { Name = "Bryter Music", Address = "Marlinspike Hall", Town = "Suffolk" });
                //CompanyData.Add(new Company() { Name = "The Headline Agency", Address = "39 Churchfields", Town = "Ireland" });
                //CompanyData.Add(new Company() { Name = "MP Promotions", Address = "13 Greave", Town = "Cheshire" });
                //CompanyData.Add(new Company() { Name = "Modo Production Ltd", Address = "Ground Floor", Town = "London" });
                //CompanyData.Add(new Company() { Name = "Nomadic Music", Address = "Unit 18", Town = "London" });
                //CompanyData.Add(new Company() { Name = "Reverb Records Ltd", Address = "Reverb House", Town = "London" });
                //CompanyData.Add(new Company() { Name = "SIBC", Address = "Market Street", Town = "Lerwick" });
                //CompanyData.Add(new Company() { Name = "Marken Time Critical Express", Address = "Unit 2", Town = "Isleworth" });
                //CompanyData.Add(new Company() { Name = "102.2 Smooth FM", Address = "26-27 Castlereagh Street", Town = "London" });
                //CompanyData.Add(new Company() { Name = "Chesterfield Arts Centre", Address = "Chesterfield College", Town = "Derbyshire" });
                //CompanyData.Add(new Company() { Name = "The National Indoor Arena", Address = "King Edward's Road", Town = "West Midlands" });
                //CompanyData.Add(new Company() { Name = "Salisbury City Hall", Address = "Malthouse Lane", Town = "Wiltshire" });
                //CompanyData.Add(new Company() { Name = "Minder Music", Address = "", Town = "" });
            }
            return CompanyData;
        }
    }
}

